### ISSUE TITLE
Strange page layout on chrome

### ISSUE THREAD

**Issue by avivajpeyi** [FIT3170-FY-Project-7/RABIT-COMMON#11]
<img width="1210" alt="Screen Shot 2022-09-09 at 3 33 01 pm" src="https://user-images.githubusercontent.com/15642823/189278335-5f85175c-c9e9-48e8-8efc-a1206b3e40dc.png">

<img width="1212" alt="Screen Shot 2022-09-09 at 3 33 13 pm" src="https://user-images.githubusercontent.com/15642823/189278346-9ea0aee7-42d5-4277-bca4-5370edc902bb.png">

**Comment by avivajpeyi** [comment]
Same thing happens on the 'plots' page 

<img width="1201" alt="Screen Shot 2022-09-09 at 3 34 38 pm" src="https://user-images.githubusercontent.com/15642823/189278516-9abd5887-3317-407d-8ed0-211f85ecd44c.png">

**Comment by megascrapper** [comment]
Yes this is an issue on all browsers when the windows width is below a certain size. I don't know when this starts to occur, but it happens on the version in M2. 

Probably just need to hide the sidebar on narrower windows.
