### ISSUE TITLE
Upload button not working? 

### ISSUE THREAD

**Issue by avivajpeyi** [FIT3170-FY-Project-7/RABIT-COMMON#15]
I just tried to upload the same json i set you folks (after editing the Nan). However, when I click upload, nothing happens?

<img width="1384" alt="Screen Shot 2022-09-09 at 4 47 12 pm" src="https://user-images.githubusercontent.com/15642823/189288650-7d65045c-b7b7-4dd6-9052-8e1851f1c037.png">

**Comment by megascrapper** [comment]
Which version is this?
